In [39]:
import pandas as pd
import scipy
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder  
import seaborn as sns

In [74]:
# preparating of dataframe using the data at given link and defined columns list
labels = ["gender","age","openness","neuroticism","conscientiousness","agreeableness","extraversion","Personality"]
dataframe = pd.read_csv("psyc.csv", names=labels)

# converting gender F/M to 0/1
le = LabelEncoder()
dataframe["gender"] = le.fit_transform(dataframe["gender"])

# separating out personality col and other cols
newDF, personality = dataframe.iloc[:, :-1], dataframe.iloc[:,-1]
array = newDF.values

# separate array into input and output components
X = array[:,0:8]
Y = array[:,8:]
 
# initialising the MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
# learning the statistical parameters for each of the data and transforming
rescaledX = scaler.fit_transform(X)
 
# summarize transformed data
np.set_printoptions(precision=3)
print(rescaledX[0:5,:])

dataframe

[[0.    0.652 0.857 1.    1.    0.571 0.571]
 [1.    0.522 0.571 0.375 0.5   0.143 0.429]
 [0.    0.87  0.571 0.5   0.75  0.143 0.429]
 [0.    0.565 0.714 0.125 0.75  0.429 0.857]
 [0.    0.609 0.143 0.375 0.75  0.    0.286]]


gender  age  openness  neuroticism  conscientiousness  agreeableness  \
0         0   20         7            9                  9              5   
1         1   17         5            4                  5              2   
2         0   25         5            5                  7              2   
3         0   18         6            2                  7              4   
4         0   19         2            4                  7              1   
..      ...  ...       ...          ...                ...            ...   
310       0   19         6            5                  6              4   
311       1   18         2            5                  8              3   
312       1   18         7            5                  6              2   
313       1   23         6            7                  5              4   
314       0   18         5            7                  3              5   

     extraversion  Personality  
0               5   dependable  
1               4      serious  
2               4      serious  
3               7      serious  
4               3  responsible  
..            ...          ...  
310             3  extraverted  
311             7   dependable  
312             7      serious  
313             3  extraverted  
314             6  extraverted  

[315 rows x 8 columns]